package com.vx.storage_device_monitor.dao.entity;

public enum FieldType {
    RECEIVEBANDWIDTH,TRANSMITBANDWIDTH,CPUUSAGE,MEMORYUSAGE,DISKUSAGE,TEMPERATURE,ENERGY,INPUTNUMBER,OUTPUTNUMBER,ALLFIELDS;
}
